#ifndef RESOURCEIDENTIFIERS_H_INCLUDED
#define RESOURCEIDENTIFIERS_H_INCLUDED

enum GraphicsIdentifier {
    SQUARE,
    CANON,
    CANON_BALL,
    REFRESH_BAR,
    ELEMENT_COUNT
};

enum SoundIdentifier {
};

#endif // RESOURCEIDENTIFIERS_H_INCLUDED
